// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq2JiIV_aDRsarU_g_9_--a69SyulduEw',
    appId: '1:829237859997:web:5bef4842e468ccefdea674',
    messagingSenderId: '829237859997',
    projectId: 'event-booking-app-a9ebe',
    authDomain: 'event-booking-app-a9ebe.firebaseapp.com',
    storageBucket: 'event-booking-app-a9ebe.firebasestorage.app',
    measurementId: 'G-2L6F12GPEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRSV7hfEUb5CWMssv1PjTZrPhjeJAESqw',
    appId: '1:829237859997:android:b237e4aeb05d96aadea674',
    messagingSenderId: '829237859997',
    projectId: 'event-booking-app-a9ebe',
    storageBucket: 'event-booking-app-a9ebe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtndI1R7Crdl2Dsea3giAovReJV5_N-A4',
    appId: '1:829237859997:ios:2ed428e7855bc2b6dea674',
    messagingSenderId: '829237859997',
    projectId: 'event-booking-app-a9ebe',
    storageBucket: 'event-booking-app-a9ebe.firebasestorage.app',
    iosBundleId: 'com.example.eventbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtndI1R7Crdl2Dsea3giAovReJV5_N-A4',
    appId: '1:829237859997:ios:2ed428e7855bc2b6dea674',
    messagingSenderId: '829237859997',
    projectId: 'event-booking-app-a9ebe',
    storageBucket: 'event-booking-app-a9ebe.firebasestorage.app',
    iosBundleId: 'com.example.eventbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq2JiIV_aDRsarU_g_9_--a69SyulduEw',
    appId: '1:829237859997:web:b1115d07576a3b26dea674',
    messagingSenderId: '829237859997',
    projectId: 'event-booking-app-a9ebe',
    authDomain: 'event-booking-app-a9ebe.firebaseapp.com',
    storageBucket: 'event-booking-app-a9ebe.firebasestorage.app',
    measurementId: 'G-R2XQBCKXTY',
  );
}
