import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/theme/app_theme.dart';
import 'features/Creator/Creator_dashboard_screen.dart';
import 'features/Creator/edit_listing_screen.dart';
import 'features/auth/login_screen.dart';
import 'features/auth/reset_password_screen.dart';
import 'features/auth/signup_screen.dart';
import 'features/auth/verification_screen.dart';
import 'features/booking/payment_screen.dart';
import 'features/booking/seat_selection_screen.dart';
import 'features/event_detail/event_detail_screen.dart';
import 'features/explore/explore_map_screen.dart';
import 'features/home/event_list_screen.dart';
import 'features/home/filter_screen.dart';
import 'features/home/main_navigation_screen.dart';
import 'features/onboarding/onboarding_screen.dart';
import 'features/onboarding/splash_screen.dart';
import 'features/profile/profile_screen.dart';
import 'features/tickets/manage_bookings_screen.dart';
import 'features/tickets/my_tickets_screen.dart';
import 'features/tickets/ticket_detail_screen.dart';
import 'firebase_options.dart'; // 💡 Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    const ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Eventra',
      theme: AppTheme.lightTheme,
      initialRoute: '/',
      routes: {
        '/': (context) => const SplashScreen(),
        '/onboarding': (context) => const OnboardingScreen(),
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignUpScreen(),
        '/verification': (context) => const VerificationScreen(),
        '/reset-password': (context) => const ResetPasswordScreen(),
        '/home': (context) => const MainNavigationScreen(),
        '/filter': (context) => const FilterScreen(),
        '/event-detail': (context) => const EventDetailScreen(),
        '/event-list': (context) =>
            const EventListScreen(events: [], title: 'Events'),
        '/explore-map': (context) => const ExploreMapScreen(),
        '/my-tickets': (context) => const MyTicketsScreen(),
        '/profile': (context) => const ProfileScreen(),
        '/seat-selection': (context) => const SeatSelectionScreen(),
        '/payment': (context) => const PaymentScreen(),
        '/ticket-detail': (context) => const TicketDetailScreen(),
        '/manage-bookings': (context) => const ManageBookingsScreen(),
        '/Creator-dashboard': (context) => const CreatorDashboardScreen(),
        '/Creator-edit-listing': (context) => const EditReelsCreatorScreen(),
      },
    );
  }
}
